name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [submitted]

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: main
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag amirhwp/mutt
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push to Dockerhub
        run: docker push amirhwp/mutt

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            fandogh-cli
      - name: Login to Fandogh
        run: fandogh login --username "${{ secrets.FANDOGH_USERNAME }}" --password "${{ secrets.FANDOGH_PASSWORD }}"
      - name: Deploy on production
        run: echo 'y' | fandogh service reset -s "${{ secrets.FANDOGH_SERVICE }}"
