name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [submitted]

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amirhwp/mutt
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Push to Dockerhub
      run: docker push amirhwp/mutt
